<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QPhoneTextBox
Examples::AddPluginExampleFile('QPhoneTextBox', 'example/phonetextbox.php QPhoneTextBox: validate and format phone numbers');
//// END QPhoneTextBox

?>
