DROP TRIGGER IF EXISTS `surlogi1_sglbd`.`INSERTAR_FL` 
USE `surlogi1_sglbd`

CREATE TRIGGER `INSERTAR_FL` AFTER INSERT ON `LICENCIA` FOR EACH ROW BEGIN

    DECLARE done INT DEFAULT 0;
    DECLARE f INT;
    DECLARE d INT;
    DECLARE cur1
        CURSOR FOR
	SELECT idFASE from FASE,PROCESO where PROCESO.idPROCESO = FASE.PROCESO_idPROCESO and PROCESO.idPROCESO = NEW.PROCESO_idPROCESO;
    DECLARE cur2
        CURSOR FOR
	SELECT DOCUMENTOS_FASE.DOCUMENTO_idDOCUMENTO from FASE,PROCESO,DOCUMENTOS_FASE where PROCESO.idPROCESO = FASE.PROCESO_idPROCESO and DOCUMENTOS_FASE.FASE_idFASE=FASE.idFASE and PROCESO.idPROCESO = NEW.PROCESO_idPROCESO;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
    OPEN cur1;
    OPEN cur2;

    REPEAT
        FETCH cur1 INTO f;
        IF NOT done THEN
            INSERT
            INTO  FASE_LICENCIA(LICENCIA_idLICENCIA, FASE_fechaInicio, FASE_fechaFin, FASE_idFASE) VALUES (NEW.idLICENCIA,null,null,f);
        END IF;
    UNTIL
        done
    END REPEAT;
CLOSE cur1;

SET done=0;

REPEAT
        FETCH cur2 INTO d;
        IF NOT done THEN
            INSERT
            INTO  VIGENCIA_DOCUMENTO(LICENCIA_idLICENCIA,DOCUMENTOS_FASE_DOCUMENTO_idDOCUMENTO,fechaOtorgado,fechaVencimieto,numRef) VALUES (NEW.idLICENCIA,d,null,null,null);
        END IF;
    UNTIL
        done
    END REPEAT;

    CLOSE cur2;

END;