<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QPhoneTextBox
QApplicationBase::$ClassFile['qphonetextbox'] = __PLUGINS__ . '/QPhoneTextBox/includes/QPhoneTextBox.class.php';
//// END QPhoneTextBox

?>